# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: postgresql
  encoding: unicode
  
  pool: 5
 
test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  password:
